version: "3"
## src on 14
services:
    app:
        build: .
        container_name: pet_project
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - shared_bridge
        volumes:
            - "./:/usr/src/app"
            - "/uploadData:/uploadData"
    postgres:
        image: postgres
        container_name: pg_pet_project
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: $PG_DATABASE
            POSTGRES_PASSWORD: $PG_PASSWORD
            POSTGRES_USER: $PG_USER
        networks:
            - shared_bridge
        volumes:
            - "pg-data:/var/lib/postgresql/data"
volumes:
    pg-data:
        driver: local
    app-data:
        driver: local
networks:
    shared_bridge:
        driver: bridge