version: "3"

services: 
    app:
        build: .
        env_file: ./configs/.env
        ports:
            - "8080:3000"
        depends_on:
            - postgres
        networks:
            - shared_bridge
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: pet_project
            POSTGRES_PASSWORD: prodpassword
            POSTGRES_USER: postgres
        networks:
            - shared_bridge
networks:
    shared_bridge:
        driver: bridge