version: "3"
services: 
    app:
        build: .
        ports:
            - "8080:3000"
        links: 
            - "postgres"
    postgres:
        image: postgres
        ports:
            - "5432:5432"
    